# Generated by Django 5.0.7 on 2024-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='images',
            field=models.ManyToManyField(blank=True, to='image.imagesave', verbose_name='商品图片'),
        ),
    ]
