# Generated by Django 5.0.7 on 2024-08-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSave',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('id', models.CharField(editable=False, max_length=8, unique=True, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='图片')),
            ],
        ),
    ]
